# Lambda-Ping Serverless Definition.
service: monitor

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
provider:
  name: aws
  runtime: nodejs12.x

  # IAM Permissions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/lambda-monitor-${opt:stage}
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: arn:aws:sns:${opt:region, self:provider.region}:*:lambda-monitor-${opt:stage}

resources:
  Description: Check HTTP response code & latency for scheduled endpoints & send alerts to Slack
  Resources:
    MonitorDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: endpoint
            AttributeType: S
        KeySchema:
          - AttributeName: endpoint
            KeyType: HASH
        TableName: lambda-monitor-${opt:stage}
        BillingMode: PAY_PER_REQUEST
    MonitorSnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: lambda-monitor-${opt:stage}
        TopicName: lambda-monitor-${opt:stage}

# We only have the one function. In future we may add others, eg new protocol
# support if ICMP ever becomes possible on Lambda.
functions:
  http:
    handler: handler.http
    environment:
      stage: ${opt:stage}
      slackWebhookUrl: UPDATE_YOUR_SLACK_WEBHOOK HERE # https://slack.com/intl/en-ca/help/articles/115005265063-Incoming-Webhooks-for-Slack
      awsAccountId: UPDATE_YOUR_AWS_ACCOUNT_ID_HERE
    description: "Perform an HTTP request to 'ping' a remote server to determine availability"
    memorySize: 128 # MB
    timeout: 30 # seconds
    events:
      - schedule:
          name: lambda-monitor-${opt:stage}-5min
          description: 'Ping HTTP endpoints every 5 minutes'
          rate: rate(5 minutes)
          enabled: true
          input:
            - 'https://www.google.com'
            - 'https://www.tekz.io'
            - 'https://www.akki.io'
